<?xml version="1.0" ?>

<robot name="mine" xmlns:xacro="https://www.ros.org/wiki/xacro" >
  
  <xacro:property name="wheel_radius" value=".06"/>  
  <xacro:property name="wheel_length" value=".06"/>  
  <xacro:property name="box_length" value=".52"/>
  <xacro:property name="box_width" value=".32"/>
  <xacro:property name="box_height" value=".20"/>
  <xacro:property name="PI" value="3.1415"/>
  <xacro:property name="wheel_mass" value=".25"/>
  
  <xacro:include filename="$(find robot_description)/urdf/macros.xacro"/>

  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.203125 0.23828125 0.28515625 1.0"/>
  </material>
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
  </material>
  <material name="brown">
    <color rgba="0.870588235294 0.811764705882 0.764705882353 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.80078125 0.12890625 0.1328125 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>  
  
  <gazebo reference="link_chassis">
    <material>Gazebo/Orange</material>
  </gazebo>

  <!--gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">
      <alwaysOn>true</alwaysOn>
      <updateRate>20</updateRate>
      <leftJoint>joint_center_left_wheel</leftJoint>
      <rightJoint>joint_center_right_wheel</rightJoint>
      <wheelSeparation>${box_width+wheel_length}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <torque>0.1</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>link_chassis</robotBaseFrame>
      <legacyMode>true</legacyMode>
    </plugin>
  </gazebo-->
  
  <!--gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo-->
  <gazebo>
    <plugin name="diff_drive_plugin" filename="libdiffdrive_plugin_6w.so">
      <legacyMode>false</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <publishWheelJointState>true</publishWheelJointState>
      <publishOdomTF>true</publishOdomTF>
      <alwaysOn>true</alwaysOn>
      <updateRate>10.0</updateRate>
      <frontLeftJoint>joint_front_left_wheel</frontLeftJoint>
      <midLeftJoint>joint_center_left_wheel</midLeftJoint>
      <rearLeftJoint>joint_rear_left_wheel</rearLeftJoint>
      <frontRightJoint>joint_front_right_wheel</frontRightJoint>
      <midRightJoint>joint_center_right_wheel</midRightJoint>
      <rearRightJoint>joint_rear_right_wheel</rearRightJoint>
      <wheelSeparation>${box_width}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <wheelTorque>10</wheelTorque>
      <commonTopic>cmd_vel</commonTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>open</odometryFrame>
      <odometrySource>world</odometrySource>
      <robotBaseFrame>link_chassis</robotBaseFrame>
    </plugin>
    <plugin name="joint_state_publisher"
    filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>joint_front_left_wheel, joint_center_left_wheel, joint_rear_left_wheel, joint_front_right_wheel, joint_center_right_wheel, joint_rear_right_wheel</jointName>
    </plugin>
  </gazebo>
  <link name="link_chassis">
    <!-- pose and inertial -->
    <pose>0 0 ${box_height/2+.1} 0 0 0</pose>
    
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0.1"/>
      <inertia ixx="0.0395416666667" ixy="0" ixz="0" iyy="0.106208333333" iyz="0" izz="0.106208333333"/>
    </inertial>
    
    <collision name="collision_chassis">
      <geometry>
        <!--box size="${box_length} ${box_width} ${box_height}"/-->
        <mesh
          filename="package://robot_description/meshes/link_chassis.STL" />
      </geometry>
    </collision>
    
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <!--box size="${box_length} ${box_width} ${box_height}"/-->
        <mesh
          filename="package://robot_description/meshes/link_chassis.STL" />
      </geometry>
      <material name="blue"/>
    </visual>
  </link>
  <link name="metal_detector_link">
    <!--visual>
      <geometry>
        <sphere radius=".05"/>
      </geometry>
      <material name="red">
            <color rgba="1 0 0 1"/>
      </material>
    </visual-->
  </link>
  <joint name="metal_detector_joint" type="fixed">
    <origin xyz=".64 0 .06" rpy="0 0 3.1416"/>
    <parent link="link_chassis"/>
    <child link="metal_detector_link"/>

    <calibration rising="0.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="30" velocity="1.0" lower="-2.2" upper="0.7" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />
  </joint>
  <wheel wheel_prefix="center_left">
    <origin rpy="0 0 0" xyz="0 ${-box_width/2-wheel_length/2} ${-box_height/2+.05}"/>
  </wheel>
  <wheel wheel_prefix="center_right">
    <origin rpy="0 0 0" xyz="0 ${box_width/2+wheel_length/2} ${-box_height/2+.05}"/>
  </wheel>
  <wheel wheel_prefix="front_left">
    <origin rpy="0 0 0" xyz="${box_length/2-wheel_radius} ${-box_width/2-wheel_length/2} ${-box_height/2+.05}"/>
  </wheel>
  <wheel wheel_prefix="rear_left">
    <origin rpy="0 0 0" xyz="${-box_length/2+wheel_radius} ${-box_width/2-wheel_length/2} ${-box_height/2+.05}"/>
  </wheel>
  <wheel wheel_prefix="front_right">
    <origin rpy="0 0 0" xyz="${box_length/2-wheel_radius} ${box_width/2+wheel_length/2} ${-box_height/2+.05}"/>
  </wheel>
  <wheel wheel_prefix="rear_right">
    <origin rpy="0 0 0" xyz="${-box_length/2+wheel_radius} ${box_width/2+wheel_length/2} ${-box_height/2+.05}"/>
  </wheel>

</robot>

